jobs:
  include:
    - stage: check_pep8
      language: python
      python: 3.7
      before_install:
        - python -m pip install flake8
      install:
        - pip3 install --upgrade pip
        - pip install -r requirements.txt
      script:
        - ./script.sh
